Handling sql with pandas

Importing necessary libraries

In [1]:
import pandas as pd
import sqlite3

KeyboardInterrupt:

setting up the database

In [ ]:
conn = sqlite3.connect('company_sales.db')
c = conn.cursor()

In [ ]:
try:
    c.execute('''
      2 CREATE TABLE sales_data(
      3     date TEXT,
      4     region TEXT,
      5     product TEXT,
      6     quantity INTEGER,
      7     price REAL,
      8     service_receptionist TEXT
      9 )''')
except:
    print("table already created")

table already created

In [ ]:
sales = [
    ("2025-11-01", "North", "Laptop", 5, 1200.50, "Emily Clark"),
    ("2025-11-02", "South", "Smartphone", 10, 699.99, "James Lee"),
    ("2025-11-03", "East", "Headphones", 15, 89.99, "Olivia Brown"),
    ("2025-11-04", "West", "Tablet", 8, 450.00, "Noah Wilson"),
    ("2025-11-05", "Central", "Monitor", 12, 299.49, "Sophia Davis")
]

In [ ]:
c.executemany('INSERT INTO sales_data VALUES (?, ?, ?, ?, ?, ?)', sales)

now that data is loaded lets query sql

In [ ]:
pd.read_sql_query('SELECT * FROM sales_data', conn)

         date   region     product  quantity    price service_receptionist
0  2025-11-01    North      Laptop         5  1200.50          Emily Clark
1  2025-11-02    South  Smartphone        10   699.99            James Lee
2  2025-11-03     East  Headphones        15    89.99         Olivia Brown
3  2025-11-04     West      Tablet         8   450.00          Noah Wilson
4  2025-11-05  Central     Monitor        12   299.49         Sophia Davis

In [ ]:
try:
    c.execute('''CREATE TABLE product_details(product_Id INT,product_name TEXT,price REAL )''')
except:
    print("already exixsts")

already exixsts

In [ ]:
pd.read_sql_query('SELECT * FROM product_details', conn)

Empty DataFrame
Columns: [product_Id, product_name, price]
Index: []

In [ ]:
products=[(1,"Laptop",1200),
          (2,"Smartphone",699.99),
          (3,"Headphones",89.99),
          (4,"Tablet",450.00),
          (5,"Monitor",299.49)]

In [ ]:
c.executemany('INSERT INTO product_details VALUES (?, ?, ?)', products)

In [ ]:
pd.read_sql_query('SELECT * FROM product_details', conn)

   product_Id product_name    price
0           1       Laptop  1200.00
1           2   Smartphone   699.99
2           3   Headphones    89.99
3           4       Tablet   450.00
4           5      Monitor   299.49

In [ ]:
try:
    c.execute('''CREATE TABLE service_details(service_receptionist_Id INT,service_receptionist_name TEXT )''')
except:
    print("already exixsts")

In [ ]:
service=[(1,"Emily Clark"),
         (2,"James Lee"),
         (3,"Olivia Brown"),
         (4,"Noah Wilson"),
         (5,"Sophia Davis")]

In [ ]:
c.executemany('INSERT INTO service_details VALUES (?, ?)', service)

In [ ]:
pd.read_sql_query('SELECT * FROM service_details', conn)

   service_receptionist_Id service_receptionist_name
0                        1               Emily Clark
1                        2                 James Lee
2                        3              Olivia Brown
3                        4               Noah Wilson
4                        5              Sophia Davis